#ifndef CONSTANT_INCLUDED
#define CONTANT_INCLUDED
#define PIN_CODEUSE2_A 37
#define PIN_CODEUSE2_B 39
#define PIN_CODEUSE1_A 29
#define PIN_CODEUSE1_B 31

#define BRAS_GAUCHE_PIN 3
#define BRAS_GAUCHE_RETRACTED 1000
#define BRAS_GAUCHE_HALF 1500
#define BRAS_GAUCHE_EXTENDED 2000

#define BRAS_DROIT_PIN 2
#define BRAS_DROIT_RETRACTED 1000
#define BRAS_DROIT_HALF 1500
#define BRAS_DROIT_EXTENDED 2000

#define DOIGT_GAUCHE_PIN 5
#define DOIGT_GAUCHE_RETRACTED 1000
#define DOIGT_GAUCHE_HALF 1500
#define DOIGT_GAUCHE_EXTENDED 2000

#define DOIGT_DROIT_PIN 4
#define DOIGT_DROIT_RETRACTED 1000
#define DOIGT_DROIT_HALF 1500
#define DOIGT_DROIT_EXTENDED 2000

#define PINCE_GAUCHE_PIN 7
#define PINCE_GAUCHE_RETRACTED 1000
#define PINCE_GAUCHE_HALF 1500
#define PINCE_GAUCHE_EXTENDED 2000

#define PINCE_DROITE_PIN 6
#define PINCE_DROITE_RETRACTED 1000
#define PINCE_DROITE_HALF 1500
#define PINCE_DROITE_EXTENDED 2000

#endif
