#include "Mega.h"

void Mega::actuate()
{
    float m=millis();
    float dt=(m-millisActu)/1000.0;
    millisActu=m;
    //barillet.Actuate(dt);
    pinces.actuate();
    //elevator.actuate(dt);
}


void Mega::init()
{
    //elevator.init();
    brasGauche=MegaServo(BRAS_GAUCHE_PIN,BRAS_GAUCHE_RETRACTED,BRAS_GAUCHE_HALF_RETRACTED,BRAS_GAUCHE_HALF_EXTENDED,BRAS_GAUCHE_EXTENDED);
    brasDroit=MegaServo(BRAS_DROIT_PIN,BRAS_DROIT_RETRACTED,BRAS_DROIT_HALF_RETRACTED,BRAS_DROIT_HALF_EXTENDED,BRAS_DROIT_EXTENDED);
    doigtGauche=MegaServo(DOIGT_GAUCHE_PIN,DOIGT_GAUCHE_RETRACTED,DOIGT_GAUCHE_HALF_RETRACTED,DOIGT_GAUCHE_HALF_EXTENDED,DOIGT_GAUCHE_EXTENDED);
    doigtDroit=MegaServo(DOIGT_DROIT_PIN,DOIGT_DROIT_RETRACTED,DOIGT_DROIT_HALF_RETRACTED,DOIGT_DROIT_HALF_EXTENDED,DOIGT_DROIT_EXTENDED);
    pinces=Pinces(true);
    pompeG=Pompe(POMPE_GAUCHE_PIN_MOTEUR_PWR,POMPE_GAUCHE_PIN_MOTEUR_SENS,POMPE_GAUCHE_PIN_MOTEUR_BRAKE,POMPE_GAUCHE_PIN_AMP);
    pompeD=Pompe(POMPE_DROITE_PIN_MOTEUR_PWR,POMPE_DROITE_PIN_MOTEUR_SENS,POMPE_DROITE_PIN_MOTEUR_BRAKE,POMPE_DROITE_PIN_AMP);
    sharpARD=Sharp(SHARP_ARD_PIN,4242,SHARP_ANTICOL_AR_SEUIL);
    sharpARG=Sharp(SHARP_ARG_PIN,4242,SHARP_ANTICOL_AR_SEUIL);
    sharpAVD=Sharp(SHARP_AVD_PIN,SHARP_ANTICOL_AV_SEUIL_ALERT,SHARP_ANTICOL_AV_SEUIL_PROMITY);
    sharpAVG=Sharp(SHARP_AVG_PIN,SHARP_ANTICOL_AV_SEUIL_ALERT,SHARP_ANTICOL_AV_SEUIL_PROMITY);
    sharpPaletD=Sharp(SHARP_PALET_DROITE_PIN,4242,SHARP_PALET_SEUIL);
    sharpPaletG=Sharp(SHARP_PALET_GAUCHE_PIN,4242,SHARP_PALET_SEUIL);
    millisInit=millis();
    millisActu=millis();
}
